[package]
name = "rust-json"
version = "0.1.0"
authors = ["moshe.kabala@gmail.com <31233967+moshe-kabala@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
