[package]
name = "jst"
version = "0.0.1"
authors = ["moshe.kabala@gmail.com <31233967+moshe-kabala@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
readme = "readme.md"
description = "Write a javascript object in rust"

[dependencies]
num = "0.2.1"
